### ISSUE TITLE
Smart handling of ping requests - Improve performance and maybe lower needed memory

### ISSUE THREAD

**Issue by tsteur** [matomo-org/plugin-QueuedTracking#10]
In https://github.com/piwik/piwik/issues/8069 and https://github.com/piwik/piwik/issues/2041 we added support for ping requests to report a better 'time on page'. By default we send a ping request every 15 seconds. 

When this feature is used we expect the queue to get quite a few bigger in terms of needed memory. As long as we process the queue fast enough this should be ok though.

An extended version of this plugin could be really smart and "combine" or "ignore" some ping requests by only replaying the last needed "ping" request. 

Not sure how to develop it. We could either "look forward" when there is a `ping=1` if there is another one for the same visitor coming or directly when receiving a `ping=1` request instead of adding a new request to the queue update an existing request in the queue (if there is one). This can become a bit complex but can save a lot of resources and increase performance a lot as Redis is fast. Especially on high traffic websites.

**Comment by toredash** [comment]
`ping`s might have dedicated keys in Redis? Searching through a list in Redis isn't going to scale when the list is relatively long.

It should be predictable where the ping-keys are, or have a meta-key to identify what keys are present that contains ping-events. This is to avoid using the `SCAN` or `KEYS` command.

I don't know Matomo well enough, is it a problem that pings would be processed after "regular" tracking events ? Or do they need to be processed in-order ?

**Comment by tsteur** [comment]
The problem is really they need to be processed in order. And scanning through the list is slow indeed.

**Comment by toredash** [comment]
Some thoughts: 
I'm wondering if the queue logic could be rewritten if this gets merged: https://github.com/matomo-org/matomo/pull/14360

If I understand the change correctly, one could have one queue per VisitorId, rather than having a specific set of queue(s) (trackingQueueV1*). The plugin could then process one VisitorId in one worker, possibly optimising the SQL queries for that particular VisitorId. Would fix the ping issue, as each queue is assumed not to be that deep.

Each VisitorId could get their own queue, and every tracking request would add the VisitorId to a member set key via `SADD`, to keep track of what queues are present without costly KEYS / SCAN operations.

Would need the same locking mechanism thats is present today. And a LUA script to ensure an atomic operation when removing the VisitorId queue and entry via `SREM`

**Comment by tsteur** [comment]
How would you decide on which queue to work on? Which visitor to process next basically?

**Comment by toredash** [comment]
I made a complete example I believe would work.

Keys are named:
queue_<visitorID> - List, tracking data for given visitor
lock_<visitorID> - Regular Key/value, used to lock the queue for one worker
visitorIDs - Set, list of unique visitorsID pending processing

1. Adding new tracking requests
```
SADD visitorIDs "<visitorID>" \n LPUSH "queue_<visitorID>" "<tracking request, JSON payload>"
SADD visitorIDs "<visitorID #2>" \n LPUSH "queue_<visitorID #2>" "<tracking request, JSON payload>"
SADD visitorIDs "<visitorID>" \n LPUSH "queue_<visitorID>" "<tracking request, JSON payload>"
```

2. A worker to acquire/lock a queue for 120s:
````
eval "local v = redis.call('srandmember', KEYS[1]) if v == false then return 0 else local lock = redis.call('set', 'lock_' .. v, 'locked', 'EX', '120', 'NX') if lock then return v end end" 1 visitorIDs
```
Generates the key lock_<visitorID> if not present, and returns <visitorID> so the worker know which visitor to process.

3. Release lock (input visitorID: abe):
```
LLEN queue_abe
(if 0, run lua code)
eval "local count = redis.call('LLEN', 'queue_' .. KEYS[2]) if count == 0 then redis.call('DEL', 'lock_' .. KEYS[2]) return redis.call('SREM', KEYS[1], KEYS[2]) end" 2 visitorIDs abe
# returns 1 if able to remove visitorID from "visitorIDs", (nil) if not
# notice we don't delete the queue_ or lock_. Queue is already non-existing, and lock_ will time out by itself
```


Example run;
```
# Adding data to queues and register them in visitorIDs
$ echo -e "SADD visitorIDs carl\n RPUSH queue_carl json_data" | redis-cli 
(integer) 1
(integer) 1
$ echo -e "SADD visitorIDs bob\n RPUSH queue_bob json_data" | redis-cli 
(integer) 1
(integer) 1
$ echo -e "SADD visitorIDs cindy\n RPUSH queue_cindy json_data" | redis-cli 
(integer) 1
(integer) 1
$ echo -e "SADD visitorIDs abe\n RPUSH queue_abe json_data" | redis-cli 
(integer) 1
(integer) 1
$ echo -e "SADD visitorIDs abe\n RPUSH queue_abe json_data" | redis-cli 
(integer) 0
(integer) 2
$ echo -e "SADD visitorIDs abe\n RPUSH queue_abe json_data" | redis-cli 
(integer) 0
(integer) 3
$ redis-cli
127.0.0.1:6379> keys *
1) "queue_cindy"
2) "queue_carl"
3) "queue_bob"
4) "queue_abe"
5) "visitorIDs"
127.0.0.1:6379> SMEMBERS visitorIDs
1) "carl"
2) "abe"
3) "cindy"
4) "bob"
# Try to get a lock
127.0.0.1:6379> eval "local v = redis.call('srandmember', KEYS[1]) if v == false then return 0 else local lock = redis.call('set', 'lock_' .. v, 'locked', 'EX', '120', 'NX') if lock then return v end end" 1 visitorIDs
"bob"
# Lock for bob 
127.0.0.1:6379> ttl lock_bob
(integer) 109
127.0.0.1:6379> eval "local v = redis.call('srandmember', KEYS[1]) if v == false then return 0 else local lock = redis.call('set', 'lock_' .. v, 'locked', 'EX', '120', 'NX') if lock then return v end end" 1 visitorIDs
"cindy"
127.0.0.1:6379> eval "local v = redis.call('srandmember', KEYS[1]) if v == false then return 0 else local lock = redis.call('set', 'lock_' .. v, 'locked', 'EX', '120', 'NX') if lock then return v end end" 1 visitorIDs
"carl"
127.0.0.1:6379> eval "local v = redis.call('srandmember', KEYS[1]) if v == false then return 0 else local lock = redis.call('set', 'lock_' .. v, 'locked', 'EX', '120', 'NX') if lock then return v end end" 1 visitorIDs
(nil) # PS! Nothing returned here since the random key we selected was already locked
127.0.0.1:6379> eval "local v = redis.call('srandmember', KEYS[1]) if v == false then return 0 else local lock = redis.call('set', 'lock_' .. v, 'locked', 'EX', '120', 'NX') if lock then return v end end" 1 visitorIDs
"abe"
127.0.0.1:6379> eval "local v = redis.call('srandmember', KEYS[1]) if v == false then return 0 else local lock = redis.call('set', 'lock_' .. v, 'locked', 'EX', '120', 'NX') if lock then return v end end" 1 visitorIDs
(nil)
# Verify all locks are present
127.0.0.1:6379> keys *
1) "lock_abe"
2) "lock_carl"
3) "lock_bob"
4) "queue_cindy"
5) "queue_carl"
6) "lock_cindy"
7) "queue_bob"
8) "queue_abe"
9) "visitorIDs"
# Cleanup
127.0.0.1:6379> del lock_abe lock_carl lock_bob lock_cindy
(integer) 4
# Get fresh lock
127.0.0.1:6379> eval "local v = redis.call('srandmember', KEYS[1]) if v == false then return 0 else local lock = redis.call('set', 'lock_' .. v, 'locked', 'EX', '120', 'NX') if lock then return v end end" 1 visitorIDs
"abe"
127.0.0.1:6379> LRANGE queue_abe 0 2
1) "json_data"
2) "json_data"
3) "json_data"
# process data, then delete it
127.0.0.1:6379> LTRIM queue_abe 2 -1
OK
127.0.0.1:6379> LLEN queue_abe
(integer) 1
# Try to delete queue
127.0.0.1:6379> eval "local count = redis.call('LLEN', 'queue_' .. KEYS[2]) if count == 0 then redis.call('DEL', 'queue_' .. KEYS[2], 'lock_' .. KEYS[2]) return redis.call('SREM', KEYS[1], KEYS[2]) end" 2 visitorIDs abe
(nil) # Does not work since there is one item in the queue left, drain queue
127.0.0.1:6379> LRANGE queue_abe 0 2
1) "json_data"
127.0.0.1:6379> LTRIM queue_abe 2 -1
OK
127.0.0.1:6379> LLEN queue_abe
(integer) 0
# Delete queue
127.0.0.1:6379> eval "local count = redis.call('LLEN', 'queue_' .. KEYS[2]) if count == 0 then redis.call('DEL', 'lock_' .. KEYS[2]) return redis.call('SREM', KEYS[1], KEYS[2]) end" 2 visitorIDs abe
(integer) 1
# Verify queue and lock is gone
127.0.0.1:6379> keys *
1) "queue_cindy"
2) "queue_carl"
3) "queue_bob"
4) "visitorIDs"
# Verify vistitorID is gone from Set
127.0.0.1:6379> SMEMBERS visitorIDs
1) "carl"
2) "cindy"
3) "bob"
```

**Comment by tsteur** [comment]
I'm not sure. Wouldn't it be less efficient since you cannot replay as many tracking requests at a time ? Eg a visitor rarely as > 10 tracking requests but you sometimes maybe want to replay 50 or 200 at once for better performance. Also I reckon it makes it slower cause there is more locking to do for every visitor, searching which visitor to process, you can't set a worker to work on a fixed queue which makes it quite fast etc.

**Comment by toredash** [comment]
It isn't easy to test the performance of this, yes. It is highly dependent on the usage of Matomo.

We have a large portion of single-page-apps, so optimising ping for us would help a lot. I recon each user generates ~25 ping events and ~25 tracking events per visit.

Since compression is added in the plugin in #101 , a lot of our scaling issues is resolved. Also using a Redis proxy (https://github.com/twitter/twemproxy) lowered our latency bigtime. Draining the queues are now not that of a concern, since we can not queue millions of requests on Redis efficiently. 

If there are any upstream efforts to improve but, let me know and I'll see what I can contribute with.
