### ISSUE TITLE
Queue processing is slower than expected

### ISSUE THREAD

**Issue by germanoeich** [matomo-org/plugin-QueuedTracking#102]
Hello. 

I'm having an issue with the processing of the queue, it's feels way slower than it should be (Taking into account the reqs/sec that the FAQ states). 

For these tests, I purged the queue and let about 660 request sets (number taken from :monitor) pile up and stopped matomo tracking all together.

The best speed I could get after about 5 runs was
```
This worker finished queue processing with 12.64req/s (10771 requests in 852.26 seconds)
```

Here are the results of :test 
```
Settings that will be used:
Backend: redis
NumQueueWorkers: 1
NumRequestsToProcess: 100
ProcessDuringTrackingRequest: 0
QueueEnabled: 1

Redis backend only settings (does not apply when using MySQL backend):
Host: 10.12.0.53
Port: 6379
Timeout: 0
Password:
Database: 8
UseSentinelBackend: 0
SentinelMasterName: mymaster

Version / stats:
PHP version: 7.3.3-1+ubuntu18.04.1+deb.sury.org+1
Uname: Linux matomo 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64
PHPRedis version: 4.3.0
Backend version: 4.0.9
Memory: array (
  'used_memory' => 435076240,
  'used_memory_human' => '414.92M',
  'used_memory_rss' => 1375367168,
  'used_memory_rss_human' => '1.28G',
  'used_memory_peak' => 17023605528,
  'used_memory_peak_human' => '15.85G',
  'used_memory_peak_perc' => '2.56%',
  'used_memory_overhead' => 41725186,
  'used_memory_startup' => 782512,
  'used_memory_dataset' => 393351054,
  'used_memory_dataset_perc' => '90.57%',
  'total_system_memory' => 25251266560,
  'total_system_memory_human' => '23.52G',
  'used_memory_lua' => 40960,
  'used_memory_lua_human' => '40.00K',
  'maxmemory' => 0,
  'maxmemory_human' => '0B',
  'maxmemory_policy' => 'noeviction',
  'mem_fragmentation_ratio' => 3.16,
  'mem_allocator' => 'jemalloc-3.6.0',
  'active_defrag_running' => 0,
  'lazyfree_pending_objects' => 0,
)
MaxMemory Eviction Policy config: noeviction
MaxMemory config: 0

Performing some tests:
Redis is connected: 1
Connection works in general
Success for method set(testKey, value)
Success for method setnx(testnxkey, value)
Success for method setex(testexkey, 5, value)
Success for method set(testKeyWithNx, value, Array)
Success for method set(testKeyWithEx, value, Array)
Initial expire seems to be set correctly
setIfNotExists works fine
expireIfKeyHasValue seems to work fine
Extending expire seems to be set correctly
expireIfKeyHasValue correctly expires only when the value is correct
Expire is still set which is correct
deleteIfKeyHasValue seems to work fine
List feature seems to work fine

Done
```

Machine specs:
All machines are ESXi VMs running off E5-2660V2 (2.2GHz, 3.0GHz turbo) cpus, all cores are dedicated to the VM and are not shared across machines.

The worker is running off a 2vCPU 8GB ram VM and does not use more than 15% cpu when processing.
Our Redis instance has plenty of resources and is far from being overwhelmed.
The machines are connected through a 10Gbps LAN that is not being satured.

We can't spawn more workers since UserID is needed for our metrics to be relevant. Is there any way to speed up the processing? If we can get to 150-200 reqs/sec, it should be enough for us to ship metrics from all our services and use QueuedTracking to process them.

Also, when I turn off the queue, Matomo is able to process all the incoming requests on spot without issues, so I assume our MariaDB instance is holding fine. Resource-wise, there's no bottlenecking going on with the database.

Thanks for the time

**Comment by tsteur** [comment]
Did you track the requests through log importer? It isn't really recommended to use log importer plus queued tracking. Or are you using bulk tracking?

Otherwise hard to say what the bottleneck could be. It should be for sure a lot faster.

What speed do you get when using MySQL as backend for the queued tracking? Maybe this will show if you have a problem with redis.

**Comment by germanoeich** [comment]
I am not using log importer, but I am bulk tracking (shipping bulks every
10s to matomo).

Im gonna test with Mysql tomorrow and will report back. Thanks.

**Comment by tsteur** [comment]
Do you have any update @germanoeich ?

**Comment by germanoeich** [comment]
Hey. I'm deeply sorry but we ended up not going forward with matomo, I can't reproduce this bug anymore, so I'm closing this. Thanks
