### ISSUE TITLE
TLS connexion for Redis

### ISSUE THREAD

**Issue by FlorentPoinsaut** [matomo-org/plugin-QueuedTracking#108]
Hi,

It would be great that this plugin support TLS connexion between the client and the Redis server.
With the ability to set the CA, certificate and key file :-)
Per example, to be compliante with Redis Labs solutions.

Thanks in advance.

Regards,

**Comment by atom-box** [comment]
A user asked for this today.

Apparently TLS is the only way to connect with some popular services. In this case 
the user wants queued tracking to connect to AWS ElasticCache Serverless which is TLS only.

**Comment by snake14** [comment]
Hi @atom-box . Has the customer tried prepending `tls://` to the Redis host or unix socket field in the setup? As far as I can tell by looking at the [library documentation example](https://github.com/phpredis/phpredis?tab=readme-ov-file#example-2), that should work if the certificate is setup on the server.
![image](https://github.com/matomo-org/plugin-QueuedTracking/assets/11394099/6a7288f3-4aaf-43d7-b47e-be11c6331620)

**Comment by atom-box** [comment]
That worked!  Thanks @snake14

**Comment by snake14** [comment]
Hi @FlorentPoinsaut . It looks like [my suggestion](https://github.com/matomo-org/plugin-QueuedTracking/issues/108#issuecomment-2113469126) of adding `tls://` to the host URL works. It does require that you have the certificate setup on your server. Is that sufficient or would you like to keep this issue open?

**Comment by AltamashShaikh** [comment]
Fixed with #241

**Comment by FlorentPoinsaut** [comment]
Hello,
I don't have this configuration any more, but thanks all the same for your work!
Thank you very much,
