### ISSUE TITLE
Downloaded plugins using MATOMO_PLUGIN_DIRS and MATOMO_PLUGIN_COPY_DIR are not loaded correctly

### ISSUE THREAD

**Issue by nabiltntn** [matomo-org/plugin-QueuedTracking#109]
I am using new the environnement variables `MATOMO_PLUGIN_DIRS` and `MATOMO_PLUGIN_COPY_DIR` to download plugins into custom folder and load them. 

The values i am using for my example are :
- **MATOMO_PLUGIN_DIRS** : /var/www/html/additional-plugins;./additional-plugins
- **MATOMO_PLUGIN_COPY_DIR** : /var/www/html/additional-plugins/

When i download **QueuedTracking** from marketplace, installation and activation are OK, but when i try to apply and save configuration for this plugin under `General Settings` using Sentinel values, i am getting the following error in network  response tab :

```
{"result":"error","message":"Class 'Credis_Client' not found"}
```
**Credis_Client** class in defined in Client.php under plugin's libs folder.

When i install the plugin without those env vars ( so under Matomo /plugins folder ) , the configuration is saved correctly.

It looks like plugins are not fully loaded when using custom folders.

Version: 3.11.0
Plugin : QueuedTracking

**Comment by tsteur** [comment]
Moved this issue to the QueuedTracking plugin. The problem are these three lines: https://github.com/matomo-org/plugin-QueuedTracking/blob/3.3.5/Queue/Backend/Sentinel.php#L17-L19 
which expect the plugin to be in the regular plugins directory.

I haven't tested but I suppose something like this should work:

```
include_once __DIR__ . '../../libs/credis/Client.php';
include_once __DIR__ . '../../libs/credis/Cluster.php';
include_once __DIR__ . '../../libs/credis/Sentinel.php';
```

Not sure if this always works with symlinks though etc? I remember we've had some issues there before. In the worst case we would need to do something like this

```php
if (file_exists( __DIR__ . '../../libs/credis/Client.php'))  {
    include_once __DIR__ . '../../libs/credis/Client.php';
    include_once __DIR__ . '../../libs/credis/Cluster.php';
    include_once __DIR__ . '../../libs/credis/Sentinel.php';
} else {
    include_once PIWIK_INCLUDE_PATH . '/plugins/QueuedTracking/libs/credis/Client.php';
    include_once PIWIK_INCLUDE_PATH . '/plugins/QueuedTracking/libs/credis/Cluster.php';
    include_once PIWIK_INCLUDE_PATH . '/plugins/QueuedTracking/libs/credis/Sentinel.php';
}
```

**Comment by tsteur** [comment]
Do you mind testing it @nabiltntn ?

**Comment by nabiltntn** [comment]
It works with a slightly little change for the path :
```php
include_once __DIR__ . '/../../libs/credis/Client.php';
include_once __DIR__ . '/../../libs/credis/Cluster.php';
include_once __DIR__ . '/../../libs/credis/Sentinel.php';
```

I will create a PR with this fix, Any chance it could get merged soon ?

Thanks

**Comment by tsteur** [comment]
Merged it 👍
