### ISSUE TITLE
Does Processor.php log shouldn't be info instead of debug?

### ISSUE THREAD

**Issue by lockland** [matomo-org/plugin-QueuedTracking#114]
This plugin is extremelly usuful and work amazing in many cases, but on a high traffic server it doesn't work properly sometimes and We have not enough information to debug.

On an example below we have a info debug message, but even I'd actived debug level on config.ini.php and a log_writers to file, those messages aren't logging on file. So my question is, Does that information shouldn't use a log object from container instead of Common::printDebug thus this method is deprecated and use a info level?

https://github.com/matomo-org/plugin-QueuedTracking/blob/ac91672fde7a62b66c7537a00f68e22efc1908a4/Queue/Processor.php#L99

**Comment by tsteur** [comment]
@lockland with Matomo 3.12 I think there were some changes and I think it maybe working then. You will need to enable the tracker debug setting though very likely. This is either in your `config/config.ini.php`:

```
[Tracker]
debug=1
```

or you boot temporarily a `bootstrap.php` file in your root Matomo directory with the content `<?php $GLOBALS['PIWIK_TRACKER_DEBUG'] = true; ?>` (untested though if that works)
