### ISSUE TITLE
Question about batch size

### ISSUE THREAD

**Issue by mikkeschiren** [matomo-org/plugin-QueuedTracking#116]
The plugin has this hardcoded value:
```
        $processor->setNumberOfMaxBatchesToProcess(500);
```
And I'm a bit unsure how it's used, and why it is not an setting?

**Comment by tsteur** [comment]
I'm not sure I remember correctly... I reckon it's simply there to not run forever, and to prevent memory leaks / not needing to think about it etc. As we usually advice to launch a worker every minute it would quickly start the next worker once this limit has been reached. Feel free to create a PR if you feel the value doesn't work for you. Could also set it to 1000 or something.
