### ISSUE TITLE
Cookie usage

### ISSUE THREAD

**Issue by jloh** [matomo-org/plugin-QueuedTracking#51]
If I activate this plugin will the "do not track" cookie that you can set from the Piwik interface still work? Or will these visits get tracked?

**Comment by mattab** [comment]
Yes the opt out cookie should work. Can you double check and report if it's not working?

**Comment by tsteur** [comment]
I had a look in the code and actually not sure if it's working but have not tested it. There's a chance we lose the cookie information when actually inserting the requests

**Comment by jloh** [comment]
Yeah, I just tested and the opt-out cookie doesn't work when using this. My views get tracked as if I'm a normal visitor.

**Comment by wronan** [comment]
Same goes for 'use_third_party_id_cookie'.
https://github.com/piwik/piwik/blob/3.x-dev/config/global.ini.php#L595

Cookie _pk_uid is issued by the tracker, it should be sent back to the browser but it's not since the response 'stays' in Redis. So on another website, browser doesn't send it to the tracker since it didn't receive it in the first place.

**Comment by MichaelHeerklotz** [comment]
These two patches to piwik core and the plugin should fix the cookie problem. Works fine on my test setup. 

[fix_cookies.zip](https://github.com/piwik/plugin-QueuedTracking/files/1034292/fix_cookies.zip)

**Comment by wronan** [comment]
Thx man. I fixed that in similar way:

```
        $requests = $requestSet->getRequests();
        foreach ($requests as $request) {
            $request->setThirdPartyCookie($request->getVisitorId());
        }
```
was added here https://github.com/piwik/plugin-QueuedTracking/blob/master/Tracker/Handler.php#L44
Seems to do the job (without generating new visitorId or Piwik's core alternation. I'm thinking now about some system test and maybe will introduce a PR.

**Comment by MichaelHeerklotz** [comment]
@wronan 
Yes, you are right, "$request->getVisitorId()" is better than generating a new visitor id.
But without the changes to piwik core, piwik will not pick up the cookies (as I understand it).
If you only apply your change, the $_COOKIE variable will be empty when the processor is run by the cron job, or will always contain the cookie data from the user that triggered the bulk processing.

I think we relly need these changed here:
```
    private function resetEnvironment($env)
    {
        $_SERVER = $env['server'];
        $_COOKIE = $env['cookie'];
    }

    private function getCurrentEnvironment()
    {
        return array(
            'server' => $_SERVER,
            'cookie' => $_COOKIE
        );
    }
```
Or am I missing something?

**Comment by MichaelHeerklotz** [comment]
Updated patches with @wronan 's solution and the piwik core fix for $_COOKIE:
[fix_cookies_v3.zip](https://github.com/piwik/plugin-QueuedTracking/files/1035624/fix_cookies_v3.zip)

**Comment by tsteur** [comment]
Yes the `resetEnvironment` is the way to go

**Comment by wronan** [comment]
@MichaelHeerklotz - you are of course right - without env reset all visitors idvisitor is wrong.
Your solution works OK. Ours combined - like a charm :)
I just hoped it can be done without core alternation.

So what now? Will you like to create those PRs or should I? We also need some sys tests for those changes. I will write some if you won't.

**Comment by mattab** [comment]
closing as it looks like it was fixed. please re-open if this is still an  issue?
