### ISSUE TITLE
How to set the REDIS HOST value inside a config file please?

### ISSUE THREAD

**Issue by lakano** [matomo-org/plugin-QueuedTracking#63]
Hi,

We use Matomo under a Docker environment, so the Redis service is isolated inside a independant container attached to a different IP address (but on the same server technically) generated dynamically. So this IP address could change after some deploy. 

There is a solution to set the host address inside the /console command please or inside a configuration file?

**Comment by tsteur** [comment]
In your config/config.ini.php you can set the following:

```
[QueuedTracking]
numQueueWorkers = ...
numRequestsToProcess = ...
queueEnabled = ...
redisDatabase = ...
redisHost = ...
redisPassword = ...
redisPort = ...
sentinelMasterName = ...
useSentinelBackend = ...
```

See https://$YOURMATOMODOMAIN/index.php?module=Diagnostics&action=configfile&idSite=1&period=day&date=yesterday
