### ISSUE TITLE
Plugin status

### ISSUE THREAD

**Issue by garnett2125** [matomo-org/plugin-QueuedTracking#64]
Hi,

I wanted to know the status of this project please. Is this comment:
"This plugin is currently BETA and there might be issues causing not tracked requests, wrongly tracked requests or duplicated tracked requests." 
still on going ? Because I see the current version is 3.1.0 and I see no BETA.

Thanks for the feedback.

**Comment by tsteur** [comment]
It is not in BETA anymore. Thanks for pointing it out. I'll update it.
