### ISSUE TITLE
old ip address showing for redis queue

### ISSUE THREAD

**Issue by lgwapnitsky** [matomo-org/plugin-QueuedTracking#65]
We just moved our redis and piwik servers to a new IP range, and I've gone through all config files, but piwik is still showing the old address as the queue location, I've even gone into the database and manually changed it.

Is there a location that I'm missing? Config.ini.php and redis.conf have been changed

Environment is 2 piwik servers, 1 mysql db, 1 redis

![chrome_2018-02-11_14-54-24](https://user-images.githubusercontent.com/647444/36077660-98f28ea2-0f3b-11e8-9746-08dbed5098f1.png)
![mremoteng_2018-02-11_14-54-08](https://user-images.githubusercontent.com/647444/36077661-98fbb266-0f3b-11e8-805b-4893d75fb7b4.png)

**Comment by tsteur** [comment]
In case it is configured in the config, you will only need to update the config entry in the config on all servers.

If it is configured using the Matomo UI, you may have to delete the caches just to be sure using `./console cache:clear` although this should be done automatically when the settings are updated in the UI.

**Comment by lgwapnitsky** [comment]
actually had to deactivate and reactivate the plugin on all servers.  odd!

**Comment by tsteur** [comment]
👍  might be cache related.
