### ISSUE TITLE
Redis Sentinel configured, but queuedtracking:test "failing"

### ISSUE THREAD

**Issue by lgwapnitsky** [matomo-org/plugin-QueuedTracking#68]
Seeing a high number of requests coming in to the plugin after upgrading, recently, effectively "killing" my system at times. When I run the test command, I see an error with Test::getRedisConfig() even though it reports that Redis is configured. Advice requested, please.

> Version / stats:
PHP version: 7.0.25-0ubuntu0.16.04.1
Uname: Linux thnpiwik01 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64
Backend is using sentinel
Redis version: 4.0.8
Memory: array (
  'used_memory' => 358709712,
  'used_memory_human' => '342.09M',
  'used_memory_rss' => 405786624,
  'used_memory_rss_human' => '386.99M',
  'used_memory_peak' => 376991192,
  'used_memory_peak_human' => '359.53M',
  'used_memory_peak_perc' => '95.15%',
  'used_memory_overhead' => 2016352,
  'used_memory_startup' => 765656,
  'used_memory_dataset' => 356693360,
  'used_memory_dataset_perc' => '99.65%',
  'total_system_memory' => 4107702272,
  'total_system_memory_human' => '3.83G',
  'used_memory_lua' => 35840,
  'used_memory_lua_human' => '35.00K',
  'maxmemory' => 0,
  'maxmemory_human' => '0B',
  'maxmemory_policy' => 'noeviction',
  'mem_fragmentation_ratio' => '1.13',
  'mem_allocator' => 'jemalloc-4.0.3',
  'active_defrag_running' => 0,
  'lazyfree_pending_objects' => 0,
)
Uncaught exception: Argument 1 passed to Piwik\Plugins\QueuedTracking\Commands\Test::getRedisConfig() must be an instance of Redis, instance of Credis_Client given, called in /opt/piwik/plugins/QueuedTracking/Commands/Test.php on line 99
in /opt/piwik/plugins/QueuedTracking/Commands/Test.php line 200
#0 /opt/piwik/plugins/QueuedTracking/Commands/Test.php(99): Piwik\Plugins\QueuedTracking\Commands\Test->getRedisConfig(Object(Credis_Client), 'maxmemory-polic...')
#1 /opt/piwik/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\QueuedTracking\Commands\Test->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /opt/piwik/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /opt/piwik/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Piwik\Plugins\QueuedTracking\Commands\Test), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 [internal function]: Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /opt/piwik/core/Console.php(80): call_user_func(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /opt/piwik/core/Access.php(469): Piwik\Console->Piwik\{closure}()
#7 /opt/piwik/core/Console.php(81): Piwik\Access::doAsSuperUser(Object(Closure))
#8 /opt/piwik/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /opt/piwik/console(27): Symfony\Component\Console\Application->run()
#10 {main}
root@thnpiwik01:/opt/piwik#

**Comment by tsteur** [comment]
I just checked and noticed this is a bug. 

Can you try to apply the changes in https://github.com/matomo-org/plugin-QueuedTracking/pull/69/files in your file in `plugins\QueuedTracking\Commands\Test.php` to see if it fixes the issue? Basically you need to remove the word `\Redis` twice.

**Comment by tsteur** [comment]
Will close it for now as we merged the change from the previous comment. If this eventually still happens we need to have another look
