### ISSUE TITLE
Add a one-time queue size command.

### ISSUE THREAD

**Issue by software-opal** [matomo-org/plugin-QueuedTracking#77]
We're trying to integrate monitoring of the queue size into Icinga and it would be really helpful if there was a way to output only one iteration of the `monitor` command.

**Comment by tsteur** [comment]
👍 be really helpful indeed. would it only need one number for one specific queue?

**Comment by leesdolphin** [comment]
I was just thinking the current command, but instead of running in a `while 1` loop; exiting after the first print.
