### ISSUE TITLE
Queues are unevenly emptied

### ISSUE THREAD

**Issue by leesdolphin** [matomo-org/plugin-QueuedTracking#78]
We're running this on module with Redis on a server that gets about 30 requests/second; and with 4 queues we notice that one queue will end up practically empty whilst the others continue to grow.

I believe the problem lies in the handling of near-empty queues [here](https://github.com/matomo-org/plugin-QueuedTracking/blob/49f681d6d791bf017d4e457cfc5b95f1e7afa1e9/Queue/Processor.php#L103).

I think the best way to handle this when a queue is empty it should only break out of the `for` loop to allow this run to handle the other queues.

**Comment by tsteur** [comment]
BTW: Not sure if that helps... have you seen we have added recently a `--queue-id=` parameter to `:process` command? Yo could basically set up cronjobs like this:

```
* * * * * ...:process --queue-id=0
* * * * * ...:process --queue-id=1
* * * * * ...:process --queue-id=2
* * * * * ...:process --queue-id=3
```

Depending on the number of workers. This turns out quite faster as we don't have to do certain actions regularly and don't always need to look for which queue can be worked on next.

**Comment by leesdolphin** [comment]
I'm keen to avoid doing that as I'd like to have the queue count configured in one place.

The sort of problem I'm having lo a queue list that looks like `20228 (13223+6864+3+10+59+24+22+23)` Tha's down from 80,000 from about an hour ago; but that biasing is concerning

**Comment by leesdolphin** [comment]
So applying #80 cleared that queue in about 10 minutes as it had more opportunities to process requests from that first queue

**Comment by tsteur** [comment]
> I'm keen to avoid doing that as I'd like to have the queue count configured in one place.

OK. Just suggested it as it would not only make tracking faster but likely also solves your problem. I'll have a look at the PR
