### ISSUE TITLE
Scheduler: executing task Piwik\Plugins\PrivacyManager\Tasks.deleteLogData

### ISSUE THREAD

**Issue by asyslinux** [matomo-org/plugin-QueuedTracking#82]
Trouble:

With our 1 000 000 000 actions per month on web site we have issue with deleting old log data.

Can be make data deletion multithreaded? Because first task to delete old logs does not finish, as the next task begins. I installed now once a week the removal of old data, but I do not know will cross in a week again the task or not.

A very large amount of time occupies queries:

In this file:

core/DataAccess/RawLogDao.php 

This function:

protected function insertActionsToKeep($maxIds, $olderThan = true, $insertIntoTempIterationStep = 100000)

Queries like:

root@anl:/root# strace -s 8192 -p 40120
strace: Process 40120 attached
restart_syscall(<... resuming interrupted poll ...>) = 1
recvfrom(6, ";\0\0\1\0\t\0\2\10\377\3773Records: 100000  Duplicates: 99991  Warnings: 99991", 19902, MSG_DONTWAIT, NULL, NULL) = 63
sendto(6, "\232\0\0\0\3INSERT IGNORE INTO tmp_log_actions_to_keep SELECT idaction_name_ref FROM log_link_visit_action WHERE idlink_va >= '485300000' AND idlink_va < '485400000'", 158, MSG_DONTWAIT, NULL, 0) = 158

Thank You.

**Comment by asyslinux** [comment]
Can I modify this function?
protected function insertActionsToKeep($maxIds, $olderThan = true, $insertIntoTempIterationStep = 100000)

To:

protected function insertActionsToKeep($maxIds, $olderThan = true, $insertIntoTempIterationStep = 10000000)

May be this increase performance?  This will not break anything?

**Comment by tsteur** [comment]
I think this is the wrong repository for this issue. Anyway, you will need to try if it breaks anything or increases performance as this would be very much environment specific etc and it is hard to make a general statement. Tracking that many actions per month you may want to also get in touch with Matomo support: https://matomo.org/support/
