### ISSUE TITLE
QueuedTracking with MySQL - events not added to the queue?

### ISSUE THREAD

**Issue by mplackowski** [matomo-org/plugin-QueuedTracking#83]
Hi, I'm facing an issue after turning on the QueuedTracking with MySQL db.

Once it is turned on, I can't see the events anywhere: in raw DB tables, in console queuedtracking:print-queued-requests or in console  queuedtracking:monitor 

When the queue is turned off all events are logged perfectly.
I'm using Matomo 3.5.1 on Amazon Linux (Lightsail)

Here is the output of console queuedtracking:test: 

```
Settings that will be used:
Backend: mysql
NumQueueWorkers: 1
NumRequestsToProcess: 1
ProcessDuringTrackingRequest: 1
QueueEnabled: 1

Redis backend only settings (does not apply when using MySQL backend):
Host: 127.0.0.1
Port: 6379
Timeout: 0
Password:
Database: 0
UseSentinelBackend: 0
SentinelMasterName: mymaster

Version / stats:
PHP version: 7.0.30
Uname: Linux ip-xxxxxxx 4.14.26-46.32.amzn1.x86_64 #1 SMP Fri Mar 30 22:29:54 UTC 2018 x86_64
Backend version: 5.5.60
Memory: array (
  'used_memory_human' => 'disabled',
  'used_memory_peak_human' => 'disabled',
)

Performing some tests:
Connection works in general
Uncaught exception: Call to a member function rowCount() on boolean
in /var/www/html/piwik/plugins/QueuedTracking/Queue/Backend/MySQL.php line 319
#0 /var/www/html/piwik/plugins/QueuedTracking/Commands/Test.php(140): Piwik\Plugins\QueuedTracking\Queue\Backend\MySQL->delete('foo')
#1 /var/www/html/piwik/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\QueuedTracking\Commands\Test->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/piwik/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/piwik/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Piwik\Plugins\QueuedTracking\Commands\Test), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 [internal function]: Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/piwik/core/Console.php(80): call_user_func(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/piwik/core/Access.php(469): Piwik\Console->Piwik\{closure}()
#7 /var/www/html/piwik/core/Console.php(81): Piwik\Access::doAsSuperUser(Object(Closure))
#8 /var/www/html/piwik/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/piwik/console(27): Symfony\Component\Console\Application->run()
#10 {main}
```

I'm wondering if I missed some configuration step? The system status check is all green - no issues. 

Also I noticed that only one DB table is created after installing and activating this plugin: `matomo_queuedtracking_queue` is it correct?

**Comment by tsteur** [comment]
The triggered error actually would only occur in the test command, but not when actually executing it. Do you know if you are using mysqli?

Just to be sure: What do you mean by "events"? Tracking Matomo events for the events report? Are other tracking requests working?

**Comment by mplackowski** [comment]
So unfortunately I'm not familiar with PHP, however I used ngrok and debug that place. 
It turns out that even though the `matomo_queuedtracking_list_trackingQueueV1` table doesn't exisit the exception isn't raised. It seems like the DB query returns true when success of false when failure instead of throwing an exception? 

After I realized this I forced one time execution of this method `$this->createListTable($key);` and the table was correctly added. Now, when refreshing tracked page, I can see that new records are added, also in the queue table there is one record. 

However those events aren't processed further. When trying to process them manually with console command I got an exception pointing line 372: https://github.com/matomo-org/plugin-QueuedTracking/blob/3.2.1/Queue/Backend/MySQL.php#L372  saying that `Uncaught exception: Call to a member function rowCount() on boolean`

In the config.ini.php file I can see that the db adapter is set to 'MYSQLI'. Additionaly in Settings/Diagnostics/System Check I can see that also the PDO and PDO/MySQL extensions are installed as well. Maybe I should switch somehow to PDO and test it?

Here is the stack trace of the `console queuedtracking:process` exception:

`
[user-xxxx piwik]$ sudo ./console queuedtracking:process
Starting to process request sets, this can take a while
Uncaught exception: Call to a member function rowCount() on boolean
in /var/www/html/piwik/plugins/QueuedTracking/Queue/Backend/MySQL.php line 372
#0 /var/www/html/piwik/plugins/QueuedTracking/Queue/Lock.php(77): Piwik\Plugins\QueuedTracking\Queue\Backend\MySQL->expireIfKeyHasValue('QueuedTrackingL...', '96a3aaac3515', 30)
#1 /var/www/html/piwik/plugins/QueuedTracking/Queue/Manager.php(296): Piwik\Plugins\QueuedTracking\Queue\Lock->expireLock(30)
#2 /var/www/html/piwik/plugins/QueuedTracking/Queue/Processor.php(197): Piwik\Plugins\QueuedTracking\Queue\Manager->expireLock(30)
#3 /var/www/html/piwik/plugins/QueuedTracking/Queue/Processor.php(148): Piwik\Plugins\QueuedTracking\Queue\Processor->extendLockExpireToMakeSureWeCanProcessARequestSet(Object(Piwik\Tracker\RequestSet))
#4 /var/www/html/piwik/plugins/QueuedTracking/Queue/Processor.php(110): Piwik\Plugins\QueuedTracking\Queue\Processor->processRequestSets(Object(Piwik\Tracker), Array)
#5 /var/www/html/piwik/plugins/QueuedTracking/Commands/Process.php(80): Piwik\Plugins\QueuedTracking\Queue\Processor->process()
#6 /var/www/html/piwik/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\QueuedTracking\Commands\Process->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/piwik/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/piwik/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Piwik\Plugins\QueuedTracking\Commands\Process), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 [internal function]: Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/piwik/core/Console.php(80): call_user_func(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/piwik/core/Access.php(469): Piwik\Console->Piwik\{closure}()
#12 /var/www/html/piwik/core/Console.php(81): Piwik\Access::doAsSuperUser(Object(Closure))
#13 /var/www/html/piwik/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/piwik/console(27): Symfony\Component\Console\Application->run()
#15 {main}
PHP Fatal error:  Uncaught Error: Call to a member function rowCount() on boolean in /var/www/html/piwik/plugins/QueuedTracking/Queue/Backend/MySQL.php:345
Stack trace:
#0 /var/www/html/piwik/plugins/QueuedTracking/Queue/Lock.php(69): Piwik\Plugins\QueuedTracking\Queue\Backend\MySQL->deleteIfKeyHasValue('QueuedTrackingL...', '96a3aaac3515')
#1 /var/www/html/piwik/plugins/QueuedTracking/Queue/Manager.php(291): Piwik\Plugins\QueuedTracking\Queue\Lock->unlock()
#2 /var/www/html/piwik/plugins/QueuedTracking/Commands/Process.php(74): Piwik\Plugins\QueuedTracking\Queue\Manager->unlock()
#3 [internal function]: Piwik\Plugins\QueuedTracking\Commands\Process->Piwik\Plugins\QueuedTracking\Commands\{closure}()
#4 {main}
  thrown in /var/www/html/piwik/plugins/QueuedTracking/Queue/Backend/MySQL.php on line 345
`

**Comment by mplackowski** [comment]
I modified the config.ini.php file and set the adapter to  "PDO\MYSQL". 
No more exceptions, and queue works as expected.

From my point of view the issue can be closed. I don't know if there is some problem with MYSQLI  or maybe it was caused only by my invalid configuration.

**Comment by tsteur** [comment]
I'm reopening the issue and will provide a PR as it is supposed to work with Mysqli. Cheers for reporting the issue.

**Comment by itseoconsulting** [comment]
Hi guys,

I run into similar issues and just learning from this threat I changed before installing the plugin from MYSQLI to PDO\MYSQL and everything queue-wise was working as expected.

The only issues left, piwik.php still need a couple for hundred milliseconds to run, which is not a change compared to matomo without the plugin.

So what we need to do that you can investigate this issue and bring piwik.php down to 5-10 ms as expected with queuetracking plugin?

Please advise.

**Comment by tsteur** [comment]
> couple for hundred milliseconds to run
How do you measure this? Are you looking at server time only? Typically, even without Queued tracking a request should maybe take only 50ms, with Queued tracking about 5ms (both times depending on server). You want to make sure to measure only the time it takes on the server / in PHP.

**Comment by itseoconsulting** [comment]
Just 2 examples with Cloudflare disabled and enabled

Test from AU, server in SG

`https://matomo.celax.asia/piwik.php?action_name=Home%20%7C%20Bali%20%7C%20BiruDaun%20Web%20Studio&idsite=3&rec=1&r=899342&h=20&m=35&s=54&url=https%3A%2F%2Fwww.celax.asia%2F&_id=1e8703a23c4aedc2&_idts=1534131354&_idvc=1&_idn=0&_refts=0&_viewts=1534131354&send_image=1&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=1&java=1&gears=0&ag=0&cookie=1&res=1280x1024&gt_ms=29&pv_id=l5bwqh`

`https://tools.pingdom.com/#!/ekK9zn/https://matomo.celax.asia/piwik.php?action_name=Home%20%7C%20Bali%20%7C%20BiruDaun%20Web%20Studio&idsite=3&rec=1&r=899342&h=20&m=35&s=54&url=https%3A%2F%2Fwww.celax.asia%2F&_id=1e8703a23c4aedc2&_idts=1534131354&_idvc=1&_idn=0&_refts=0&_viewts=1534131354&send_image=1&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=1&java=1&gears=0&ag=0&cookie=1&res=1280x1024&gt_ms=29&pv_id=l5bwqh`

Even if I run a client in SG only, then it not better.

It's a Siteground Server with significant power to handle around 100K requests per second.

It's confusing.

Since we have so much delays with piwik.php, we fire the tracking code after "onLoad"

**Comment by tsteur** [comment]
I would say you definitely want Cloudflare disabled for tracking requests. In case you are familiar with PHP I recommend trying to measure how much time is spent in PHP only. Anything else we cannot influence. If you don't know how to measure the time, I'd maybe try to access your server(s) and fetch the data from there eg `time curl https://matomo.celax.asia/piwik.php?action_name=Home%20%7C%20Bali%20%7C%20BiruDaun%20Web%20Studio&idsite=3&rec=1&r=899342&h=20&m=35&s=54&url=https%3A%2F%2Fwww.celax.asia%2F&_id=1e8703a23c4aedc2&_idts=1534131354&_idvc=1&_idn=0&_refts=0&_viewts=1534131354&send_image=1&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=1&java=1&gears=0&ag=0&cookie=1&res=1280x1024&gt_ms=29&pv_id=l5bwqh` or if possible go through a local host.

**Comment by itseoconsulting** [comment]
Hi Thomas, thanks for your feedback.

this is a test and a pre-deployment server and you can look at this cPanel,
which is fresh, but matomo is slow too.

Same issue - https://tools.pingdom.com/#!/eh72A3/assorted.store

I already had a long discussion with Siteground but they told me all is
good.

Here are access details to a new cPanel at the server: Right now CloudFlare
is off for the moment.
cPanel assortedstore vOZ6!EyH$bhD https://c39165.sgvps.net:2083/
Domain

active, Google Domains DNSSEC
CloudFlare

active
WordPress adminwp 12AssortedStore34! assorted.store/wp-admin/
Matomo adminmatomo 12AssortedMatomo34! matomo.assorted.store
G Suite

active

On another cPanel we have a premium package matomo instance running. But we
use this only for 2 cPanels.

BTW are you aware that Matomo and CloudFlare Firewall do not like each
other? E.g. with formula tracking

Best

Pak Kriss

**Comment by itseoconsulting** [comment]
Warum schreibe ich eigentlich English, wenn ich gerade sehe das Du auch
Deutsch verstehst. Sag mir was Dir lieber ist. Persönlich ist mir Deutsch
lieber, da mein English nicht native ist.

**Comment by itseoconsulting** [comment]
Setup: https://www.siteground.com/dedicated-hosting.htm Europe

Here a waterfall view from Holland:
https://www.webpagetest.org/result/180815_A3_1f3d4a3aa4558ebc18de7ea0940bf8da/3/details/#waterfall_view_step1

From Canada:
https://gtmetrix.com/reports/assorted.store/h91TTWZj#waterfall

From Australia: (scroll a little bit down)
https://tools.pingdom.com/#!/eDR5gG/https://assorted.store

In all cases piwik.php is not very fancy.

Please let us know how we can support you to bring QueuedTracking with mysqli on the road?

Please advise.

**Comment by tsteur** [comment]
Released an update which supports MySQLi. As mentioned Queued Tracking will take only a few ms as all it does is accepting the request and inserting it into the DB basically. You will need to ideally measure the time that it spends in PHP only. If it is still slow, check if the queue table (name contains `queuedtracking_list_*`) contains heaps of entries (like a million). Maybe you are only writing requests into the queue but never process them. Then it may be a wee bit slower. For ultimate performance even when millions of requests are queued, consider using Redis.

**Comment by itseoconsulting** [comment]
I received the following feedback from Siteground https://www.siteground.com/dedicated-hosting.htm regarding a plain vanilla Matomo instance with QueuedTracking enabled and next to zero visitors, since this is a playground. Please advise.
__________________________________________
Hello Chris,

I checked the problem by opening https://assorted.store in Chrome. I used its developer tools to check the loaded elements where I noticed that 

https://matomo.assorted.store/piwik.php?action_name=Assorted%20Store%20%E2%80%93%20One%20Stop%20Shopping&idsite=1&rec=1&r=905039&h=9&m=14&s=36&url=https%3A%2F%2Fassorted.store%2F&_id=a4423fef809962d0&_idts=1535350476&_idvc=1&_idn=0&_refts=0&_viewts=1535350476&send_image=1&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=1&java=0&gears=0&ag=0&cookie=1&res=1280x800&gt_ms=2238&pv_id=UA8Mat

took longer than 100 ms. The suggested by developer "time curl" command for this URL returns the following: 

Code:
real	0m0.460s
user	0m0.028s
sys	0m0.018s

At this point I don't see any problem with the server response time as the test phpinfo() script returns output pretty fast. Its "time curl" output shows: 

Code:
real	0m0.134s
user	0m0.005s
sys	0m0.008s

At this point I think that the slow execution of piwik.php comes from the php code itself which this script contains, but we are not professional developers and it is outside our skills to debug it further. If the script developer suggests some kind of server side tweak to improve the loading time, please let us know and we will gladly implement the necessary changes. 

Best Regards, 

Yavor I.
Senior Technical Support
