### ISSUE TITLE
Data Size in Redis - List Key trackingQueueV1

### ISSUE THREAD

**Issue by siva538** [matomo-org/plugin-QueuedTracking#86]
Hi - Thanks for the amazing plugin for an amazing tool. To make this even beautiful would like to request an enhancement for compressing the contents of trackingQueueV1, trackingQueueV1_2 etc. 

currently this is consuming 2.7x KB of data for each request being tracked, If there are millions of requests, this would go to the order of 2-3 GB. We are planning to queue good amount of requests (in order millions per day) and would like to process them through nightly cron job. 

Also you might want to include this as a configuration option as it would help any if they have any concerns with the cpu cycles (and backward compatibility). Ideally it should not eat up so much of cpu cycles just for using compression, and while decompressing the contents it anyways done as part of the cron job, so no concerns there.

As a background of this ask, we have tested similar sizes data in Redis, and Redis performed really well when handling smaller sized values as compared higher sized ones. 

Am sure you would have seen this, but including here for reference - 

[http://php.net/manual/en/function.gzcompress.php](url)

Thanks again for all your work!

**Comment by siva538** [comment]
Also you might want to include this as a configuration option as it would help any if they have any concerns with the cpu cycles. 

As a background of this ask, we have tested similar sizes data in Redis, and Redis performed really well when handling smaller sized values as compared higher sized ones.

**Comment by siva538** [comment]
We are testing the performance of this plugin, and could see the slow down in the response times of Matomo, whenever there is a read happening from the Queue Processor.

In the tests we are just reading 5 key items per one cycle, and the processor takes a hard-coded value of max. 500 iterations. We have configured this cron job to be running for every 5 mins, and during the execution of the cron job, there is a latency for each of the individual requests, as Redis is single threaded, it has to wait for the rest of the commands to get completed.

It would really help if the compression is enabled, as it would reduce the load on the Redis and might slightly increase the CPU utilization on the Cron job based task server.

Thanks in advance. 

Kumar.

**Comment by tsteur** [comment]
> If there are millions of requests, this would go to the order of 2-3 GB

As memory is fairly cheap and you can store heaps of requests eg with 32, 64 or 128GB memory we haven't really looked into compression but for sure it can improve the CPU and especially memory load on redis significantly while not having any real downsides. We are doing this in the `MySQL` backend already and same could be done in the [Redis backend](https://github.com/matomo-org/plugin-QueuedTracking/blob/master/Queue/Backend/Redis.php).

Implementation for this be easy, main problem be to know whether still existing requests are compressed or not... there be two options:

* During an update compress all currently queued requests... as there might be still requests coming in during update, a very few requests might get lost
* When fetching requests from redis before we process them, always try to uncompress and if that fails, assume it is not compressed...

Probably performing the update may be easiest and keep code base clean and easy to understand.

@siva538 are you familiar with PHP and be keen to work on this?

**Comment by siva538** [comment]
Thank you @tsteur for your feedback.

We thought we would have to implement this compression in order to further enhance the performance of the processing of data in Redis. But we lately realized that the settings done for the queue size and other settings are not getting honoured in the web-servers, due to the challenge with the cache being stored for the same. Hence we observed degradation in the performance, as the setting "Process during tracking request" though it was unchecked, still it is getting used by the web-servers. 

We had to run the below command - 

./console cache:clear

Which resolved the issue for us, and the tracking of requests is real fast.

While I do have the basic knowledge to get the compression thing done, I am occupied with other priorities currently. Request you to mark this as an enhancement and will let you know if I can pick this up any soon.

Thanks again for your help with this!

**Comment by toredash** [comment]
We are currently looking into the problem ourselves. Our queue is getting pretty large when we have flash traffic, so if we are not able process the queue for lack of resources, DB being down for whatever reason, or any other reason, the queue size in redis grows quite large, relatively fast. 

I did some quick samples of tracking events in the queue just now and it seems the queue size could be reduced at least 70%, which would improve our request/s to redis alot, but also reduce our memory requirements for redis alot.

I'm not experienced with PHP so I'm not able to contribute any specific code for this, but it seems like a simple way to improve performance and reduce the amount of RAM required.

**Comment by tsteur** [comment]
What is it that you have in mind to reduce it by 70%?

**Comment by toredash** [comment]
@tsteur, tracking request data queued in Redis, thereby reducing our RAM requirements in Redis.

I recently discovered that Redis has its own compression feature for lists, "list-compression-depth" (https://rdbtools.com//docs/memory-optimizations/enable-compression-for-list/) which might help us. 

We are also looking into of we could compress tracking data before it is sent to redis in the first place. Our hopes is that is could reduce latency on redis calls and also reduce bandwidth usage to/from Redis and the expense of increased CPU usage on our webservers.

We are looking into optimisation of redis in general since we have some of the same issues described in this thread: https://forum.matomo.org/t/high-pagehit-50m-month-installation-redis-cache-bottleneck/27443

**Comment by toredash** [comment]
@siva538 

We opted to compress data before inserting it into Redis (https://github.com/matomo-org/plugin-QueuedTracking/pull/101)

We saw a huge increase in performance, reduced latency and memory consumption.

**Comment by tsteur** [comment]
fixed by https://github.com/matomo-org/plugin-QueuedTracking/pull/101

**Comment by siva538** [comment]
Hi @toredash , thank you very much for implementing this. Am glad that the idea of compressing the contents is in action and is helping the community :)

As mentioned in the below link, we initially struggled to get a control on the queue growing huge and processing the contents fast etc. 

However we have already implemented the compression feature in the Redis configuration, which helped a lot to handle the Redis memory footprint. 

[https://forum.matomo.org/t/performance-queue-processing-cron-jobs/31893](url) 

Thanks again for your efforts and help. Cheers!
