### ISSUE TITLE
Run tests against PHP 7

### ISSUE THREAD

**Issue by J0WI** [matomo-org/plugin-QueuedTracking#88]
PHP 5.6 reaches EOL by the end of the year and 5.5 is already unsupported.
See also https://github.com/matomo-org/matomo/pull/13285

https://github.com/matomo-org/plugin-QueuedTracking/blob/e538655d5a1405db6c13dcc59ca2621fe91c7d6a/.travis.yml#L5-L9

**Comment by tsteur** [comment]
Could just add 7.0 or 7.1 and see if tests work 👍

**Comment by tsteur** [comment]
Meant just as an example :)
