### ISSUE TITLE
Add support for not touching the database when there is 0 items in the queue

### ISSUE THREAD

**Issue by toredash** [matomo-org/plugin-QueuedTracking#92]
I'm using AWS RDS Serverless which have a function to automatically stop the DB instance when it has been idle for X amount of time. We use this to optimize our cost where there is no tracking events to process.

We use Redis as our backend for tracking events in QueuedTracking, with a cron-job checking the queue every minute.

One issue we have is that queuedtracking:process hits the database on every `./console queuedtracking:process`. We thought we could eliminate this by hard-coding the config of QueuedTracking in config.ini.php like so:
```
[QueuedTracking]
backend = "redis"
redisHost = "XXX.euw1.cache.amazonaws.com"
redisPort = 6379
redisDatabase = 2
redisPassword = ""
queueEnabled = true
numQueueWorkers = 4
processDuringTrackingRequest = false
numRequestsToProcess = 25
useSentinelBackend = false
sentinelMasterName = "HardCodedIn config.ini.php"
```

But this does not help, process still hits the database.

For some reason, something in `Process.php`(?) (https://github.com/matomo-org/plugin-QueuedTracking/blob/master/Commands/Process.php) triggers an connection to the Database when the queue is empty.

I think it is caused by line `$processor = new Processor($queueManager);` (https://github.com/matomo-org/plugin-QueuedTracking/blob/master/Commands/Process.php#L78), but I'm not certain. It seems the QueuedTracking plugin always connects to the database by creating a transaction (https://github.com/matomo-org/plugin-QueuedTracking/blob/master/Queue/Processor/Handler.php#L36), even if the queue is empty.

If I read the code right, Handler will query the DB via `getDB()`, which `returns return Tracker::getDatabase();`, which will actually connect to the databse (https://github.com/matomo-org/matomo/blob/1a76568aa7f85920e8f4b58e0aa2fd32f64de8ad/core/Tracker.php#L210)

I hope it is possible to add support for not touching the database if;
* all required configuration to QueuedTracking is statically configured in `config.ini.php`, *AND*
* redis is the backend, *AND
* the queues are empty and no processing of tracking events is planned

**Comment by tsteur** [comment]
That's an interesting idea. You could even stop the server for couple hours if you don't need real time and process it later. I don't think though that we will work on this too soon as it is bit edge case. Avoiding and ensuring not DB connections are made can be quite tricky under circumstances. Had a quick look and DB connections may be made from random places like the GeoProvider etc even before the QueuedTracking::Process command is executed.

Random question: If there are sometimes no tracking requests, do you actually need the Queued Tracking?

**Comment by toredash** [comment]
I made a shell script to solve this usecase:
```
#!/usr/bin/env bash

# Fetch variables from main config
redisHost=` grep '^redisHost' /var/www/html/config/config.ini.php | awk '{print $3}' `
redisDatabase=` grep '^redisDatabase' /var/www/html/config/config.ini.php | awk '{print $3}' `
numRequestsToProcess=` grep '^numRequestsToProcess' /var/www/html/config/config.ini.php | awk '{print $3}' `

queues=( `redis-cli -h $redisHost -n $redisDatabase --scan --pattern 'trackingQueueV1*'` )

if [[ ${#queues[*]} -eq 0 ]]; then
  echo "No queues present."
  exit 0
else
  for queue in ${queues[*]}; do
    queueLength=` redis-cli -h $redisHost -n $redisDatabase LLEN $queue `
    echo "Items in queue $queue: $queueLength"
    if [[ $queueLength -gt $numRequestsToProcess ]]; then
      echo "Above threshold, starting to process..."
      /var/www/html/console queuedtracking:process
      exit 0
    fi
  done
fi

echo "Nothing to process, or not enough backlog to start."
exit 0 
```

I'm not sure if you want to keep this issue open or not ?

**Comment by tsteur** [comment]
I was going to suggest to write a tool like this 👍 

Yes I'll close the issue as it's quite edge case cause the DB would be even needed as soon as someone wants to view the reporting etc. It is really cool idea though that I had never thought about it :)
