### ISSUE TITLE
Feature discussion/req: catch SIGTERM signal

### ISSUE THREAD

**Issue by toredash** [matomo-org/plugin-QueuedTracking#94]
We are running matomo in containers to scale out the load. We also run the QueuedTracking plugin in containers.

I've looked through the code, and it does not appear to me that there any code to gracefully stop an import job. If the plugin would be able to handle the signal `SIGTERM`, the plugin would be able to finish whatever tracker events it has in the queue, and then stop.

I'm not sure how critical this is, as I don't fully understand the process code (https://github.com/matomo-org/plugin-QueuedTracking/blob/master/Queue/Processor.php)

Is this something that should be present ? I'm not sure if one could get duplicates events processed if the plugin terminates abruptly.

**Comment by tsteur** [comment]
There shouldn't be any duplicate events when you terminate it abruptly cause it uses transactions.

Therefore there also shouldn't be any need to do anything special. Let me know if there would be some other reason and I'm  happy to reopen.

**Comment by toredash** [comment]
Thanks for the clarifications @tsteur !
